begin;

with hotel_rows as (
  select *
  from jsonb_to_recordset($json$
  [
    {
      "dest_slug": "resort-interior-sp",
      "slug": "royal-palm-plaza-campinas",
      "name": "Royal Palm Plaza Resort Campinas",
      "property_type": "resort",
      "price_tier": "luxury",
      "official_site_url": "https://royalpalm.com.br/viajar-com-bebe/",
      "origin_focus": "Capital de São Paulo",
      "departure_mode": "carro",
      "drive_time_from_sao_paulo_minutes": 90,
      "recommended_airport": null,
      "transfer_minutes": null,
      "direct_flight_from_sao_paulo": false,
      "has_crib": true,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": null,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": true,
      "has_copa_baby": true,
      "has_copa_baby_24h": false,
      "all_inclusive": false,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "bebês e crianças pequenas",
      "family_score": 9.2,
      "family_notes": "Uma das opções mais fortes para bebê porque a estrutura infantil aparece com bastante clareza na página oficial.",
      "main_strength": "Página oficial dedicada a viajar com bebê, com berço, banheira infantil, menu infantil, papinhas, Copa do Bebê e berçário.",
      "attention_point": "Confirmar valores, disponibilidade e regras de serviços como baby sitter e itens infantis antes de reservar.",
      "source_urls": ["https://royalpalm.com.br/viajar-com-bebe/"],
      "source_highlights": [
        "Página oficial informa estrutura planejada para famílias com bebês.",
        "Fonte oficial cita Copa do Bebê, berços, banheiras infantis e papinhas.",
        "Boa escolha para primeira viagem curta de carro saindo da capital."
      ],
      "confidence_level": "verified",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "atibaia",
      "slug": "bourbon-atibaia",
      "name": "Bourbon Resort Atibaia",
      "property_type": "resort",
      "price_tier": "upscale",
      "official_site_url": "https://www.bourbon.com.br/hoteis-e-resorts/bourbon-resort-atibaia",
      "origin_focus": "Capital de São Paulo",
      "departure_mode": "carro",
      "drive_time_from_sao_paulo_minutes": 75,
      "recommended_airport": null,
      "transfer_minutes": null,
      "direct_flight_from_sao_paulo": false,
      "has_crib": null,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": null,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": null,
      "has_copa_baby": false,
      "has_copa_baby_24h": false,
      "all_inclusive": false,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "2+ anos, com boa estrutura para família",
      "family_score": 8.9,
      "family_notes": "Muito forte para famílias que querem carro curto, recreação e estrutura infantil sem depender de voo.",
      "main_strength": "A página oficial destaca espaços Turma da Mônica, piscina com ondas, piscinas adulto e infantil e Acqua Kids indoor.",
      "attention_point": "Copa baby e serviços específicos para bebê precisam ser confirmados diretamente com o hotel.",
      "source_urls": ["https://www.bourbon.com.br/hoteis-e-resorts/bourbon-resort-atibaia"],
      "source_highlights": [
        "Fonte oficial cita Espaços Turma da Mônica.",
        "Fonte oficial cita piscina com ondas, piscinas adulto e infantil e Acqua Kids.",
        "Boa alternativa para fim de semana ou feriado curto saindo de São Paulo."
      ],
      "confidence_level": "high",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "resort-interior-sp",
      "slug": "club-med-lake-paradise",
      "name": "Club Med Lake Paradise",
      "property_type": "resort",
      "price_tier": "upscale",
      "official_site_url": "https://www.clubmed.com.br/r/lake-paradise/y",
      "origin_focus": "Capital de São Paulo",
      "departure_mode": "carro",
      "drive_time_from_sao_paulo_minutes": 75,
      "recommended_airport": null,
      "transfer_minutes": null,
      "direct_flight_from_sao_paulo": false,
      "has_crib": null,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": null,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": null,
      "has_copa_baby": false,
      "has_copa_baby_24h": false,
      "all_inclusive": true,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "4+ anos para aproveitar melhor o Mini Club",
      "family_score": 8.6,
      "family_notes": "Excelente para famílias que querem all inclusive pertinho de São Paulo, mas menos específico para bebês pequenos.",
      "main_strength": "A página oficial posiciona o resort como all-inclusive próximo da cidade de São Paulo, com atividades para toda a família.",
      "attention_point": "O Mini Club oficial é indicado para crianças de 4 a 17 anos; para bebê pequeno, confirmar estrutura de apoio antes.",
      "source_urls": ["https://www.clubmed.com.br/r/lake-paradise/y"],
      "source_highlights": [
        "Fonte oficial informa localização a cerca de 68 km da cidade de São Paulo.",
        "Fonte oficial apresenta proposta all-inclusive e atividades para toda a família.",
        "Atenção: Mini Club indicado oficialmente para 4 a 17 anos."
      ],
      "confidence_level": "high",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "resort-interior-sp",
      "slug": "mavsa-resort",
      "name": "Mavsa Resort",
      "property_type": "resort",
      "price_tier": "upscale",
      "official_site_url": "https://www.mavsaresort.com.br/all-inclusive",
      "origin_focus": "Capital de São Paulo",
      "departure_mode": "carro",
      "drive_time_from_sao_paulo_minutes": 150,
      "recommended_airport": null,
      "transfer_minutes": null,
      "direct_flight_from_sao_paulo": false,
      "has_crib": null,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": null,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": null,
      "has_copa_baby": false,
      "has_copa_baby_24h": false,
      "all_inclusive": true,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "2+ anos, famílias que aceitam estrada maior",
      "family_score": 8.3,
      "family_notes": "Boa opção all inclusive no interior, especialmente quando a família quer alimentação resolvida e estrutura de resort.",
      "main_strength": "A página oficial descreve sistema all inclusive com refeições, lanches, petiscos e bebidas incluídos.",
      "attention_point": "Estrada já exige mais planejamento de paradas para bebê; confirmar estrutura infantil específica antes da reserva.",
      "source_urls": ["https://www.mavsaresort.com.br/all-inclusive"],
      "source_highlights": [
        "Fonte oficial informa sistema all inclusive.",
        "Boa alternativa para famílias que querem resolver alimentação dentro do resort.",
        "Tempo de carro maior pede saída fora do pico e pausas planejadas."
      ],
      "confidence_level": "high",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "praia-do-forte",
      "slug": "tivoli-praia-do-forte",
      "name": "Tivoli Ecoresort Praia do Forte",
      "property_type": "resort",
      "price_tier": "luxury",
      "official_site_url": "https://www.tivolihotels.com/pt/tivoli-ecoresort-praia-do-forte/for-families",
      "origin_focus": "São Paulo com voo para Salvador",
      "departure_mode": "voo",
      "drive_time_from_sao_paulo_minutes": null,
      "recommended_airport": "Congonhas ou Guarulhos para Salvador",
      "transfer_minutes": 60,
      "direct_flight_from_sao_paulo": true,
      "has_crib": true,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": null,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": true,
      "has_copa_baby": true,
      "has_copa_baby_24h": false,
      "all_inclusive": false,
      "calm_beach": true,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "bebês, toddlers e crianças",
      "family_score": 9.1,
      "family_notes": "Muito forte para famílias com bebê que querem praia, conforto e estrutura infantil real.",
      "main_strength": "A página oficial para famílias cita Baby Experience, Baby Copa, gastronomia infantil personalizada, piscinas infantis e atividades.",
      "attention_point": "Confirmar valores, disponibilidade dos serviços e horário dos voos para evitar chegada tarde em Salvador.",
      "source_urls": ["https://www.tivolihotels.com/pt/tivoli-ecoresort-praia-do-forte/for-families"],
      "source_highlights": [
        "Fonte oficial cita Baby Experience e Baby Copa.",
        "Fonte oficial cita gastronomia infantil personalizada.",
        "Traslado a partir de Salvador precisa ser bem planejado."
      ],
      "confidence_level": "verified",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "maceio-maragogi",
      "slug": "salinas-maragogi",
      "name": "Salinas Maragogi All Inclusive Resort",
      "property_type": "resort",
      "price_tier": "upscale",
      "official_site_url": "https://www.salinas.com.br/pt/maragogi/allinclusive",
      "origin_focus": "São Paulo com voo para Recife ou Maceió",
      "departure_mode": "voo",
      "drive_time_from_sao_paulo_minutes": null,
      "recommended_airport": "Guarulhos para Recife ou Maceió",
      "transfer_minutes": 140,
      "direct_flight_from_sao_paulo": true,
      "has_crib": null,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": null,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": null,
      "has_copa_baby": false,
      "has_copa_baby_24h": false,
      "all_inclusive": true,
      "calm_beach": true,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "3+ anos ou bebês com família acostumada a traslado longo",
      "family_score": 8.0,
      "family_notes": "Ótimo resort de praia, mas o traslado longo pesa para bebês pequenos saindo de São Paulo.",
      "main_strength": "A página oficial trabalha a reserva de resort e pacote resort + aéreo, reforçando a vocação de hospedagem de destino.",
      "attention_point": "Para bebê pequeno, o traslado de Recife ou Maceió até Maragogi precisa ser o principal ponto de decisão.",
      "source_urls": ["https://www.salinas.com.br/pt/maragogi/allinclusive"],
      "source_highlights": [
        "Fonte oficial apresenta o resort em Maragogi e fluxo de reserva com crianças.",
        "Destino tende a exigir traslado longo depois do voo.",
        "Indicado quando a família prioriza praia e estrutura de resort."
      ],
      "confidence_level": "high",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "porto-de-galinhas",
      "slug": "summerville-porto-galinhas",
      "name": "Summerville All Inclusive Resort",
      "property_type": "resort",
      "price_tier": "upscale",
      "official_site_url": "https://www.summervilleresort.com.br/",
      "origin_focus": "São Paulo com voo para Recife",
      "departure_mode": "voo",
      "drive_time_from_sao_paulo_minutes": null,
      "recommended_airport": "Congonhas ou Guarulhos para Recife",
      "transfer_minutes": 55,
      "direct_flight_from_sao_paulo": true,
      "has_crib": null,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": null,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": null,
      "has_copa_baby": false,
      "has_copa_baby_24h": false,
      "all_inclusive": true,
      "calm_beach": true,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "2+ anos, famílias que querem praia com traslado moderado",
      "family_score": 8.5,
      "family_notes": "Boa combinação de praia, all inclusive e traslado mais administrável a partir de Recife.",
      "main_strength": "A página oficial destaca proposta all inclusive em Porto de Galinhas e área para crianças.",
      "attention_point": "Confirmar estrutura para bebê, horários de transfer e maré conforme idade da criança.",
      "source_urls": ["https://www.summervilleresort.com.br/"],
      "source_highlights": [
        "Fonte oficial posiciona o resort como all inclusive em Porto de Galinhas.",
        "Menu oficial tem seção de crianças.",
        "Traslado costuma ser mais curto que destinos como Maragogi."
      ],
      "confidence_level": "high",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "porto-de-galinhas",
      "slug": "enotel-porto-galinhas",
      "name": "Enotel Porto de Galinhas",
      "property_type": "resort",
      "price_tier": "upscale",
      "official_site_url": "https://www.enotel.com.br/",
      "origin_focus": "São Paulo com voo para Recife",
      "departure_mode": "voo",
      "drive_time_from_sao_paulo_minutes": null,
      "recommended_airport": "Congonhas ou Guarulhos para Recife",
      "transfer_minutes": 55,
      "direct_flight_from_sao_paulo": true,
      "has_crib": null,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": null,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": null,
      "has_copa_baby": false,
      "has_copa_baby_24h": false,
      "all_inclusive": true,
      "calm_beach": true,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "3+ anos, famílias que querem estrutura grande",
      "family_score": 8.2,
      "family_notes": "Funciona bem para família que quer resort grande, praia e all inclusive, com atenção à escala e ao barulho.",
      "main_strength": "A página oficial posiciona o complexo como resort all inclusive em Porto de Galinhas.",
      "attention_point": "Para bebê pequeno, confirmar distância do quarto, estrutura de alimentação infantil e rotina de descanso.",
      "source_urls": ["https://www.enotel.com.br/"],
      "source_highlights": [
        "Fonte oficial apresenta resorts all inclusive em Porto de Galinhas.",
        "Bom para quem quer ficar dentro de um complexo com ampla estrutura.",
        "Precisa de checagem mais fina para rotina de bebê."
      ],
      "confidence_level": "high",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "atibaia",
      "slug": "taua-resort-atibaia",
      "name": "Tauá Resort Atibaia",
      "property_type": "resort",
      "price_tier": "upscale",
      "official_site_url": "https://tauaresorts.com.br/atibaia/",
      "origin_focus": "Capital de São Paulo",
      "departure_mode": "carro",
      "drive_time_from_sao_paulo_minutes": 60,
      "recommended_airport": null,
      "transfer_minutes": null,
      "direct_flight_from_sao_paulo": false,
      "has_crib": null,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": true,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": null,
      "has_copa_baby": null,
      "has_copa_baby_24h": null,
      "all_inclusive": false,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "1+ ano, especialmente famílias que querem lazer indoor perto de São Paulo",
      "family_score": 8.8,
      "family_notes": "Opção muito forte para uma primeira viagem curta de carro, com estrutura aquática e recreação robustas.",
      "main_strength": "O site oficial destaca AquaPark Indoor, Ilha Tauá, recreação para todas as idades e restaurantes com pensão completa.",
      "attention_point": "Serviços específicos para bebê, como berço, copa baby e itens de alimentação, devem ser confirmados diretamente antes da reserva.",
      "source_urls": ["https://tauaresorts.com.br/atibaia/"],
      "source_highlights": [
        "Fonte oficial informa AquaPark Indoor e Ilha Tauá.",
        "Fonte oficial descreve recreação para todas as idades e pensão completa.",
        "Apenas 1h de São Paulo, favorecendo viagens curtas com criança pequena."
      ],
      "confidence_level": "high",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "olimpia",
      "slug": "hot-beach-resort-olimpia",
      "name": "Hot Beach Resort Olímpia",
      "property_type": "resort",
      "price_tier": "upscale",
      "official_site_url": "https://hotbeach.com.br/hot-beach-resort/",
      "origin_focus": "Capital de São Paulo",
      "departure_mode": "carro",
      "drive_time_from_sao_paulo_minutes": 300,
      "recommended_airport": "São José do Rio Preto",
      "transfer_minutes": 50,
      "direct_flight_from_sao_paulo": false,
      "has_crib": null,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": true,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": null,
      "has_copa_baby": false,
      "has_copa_baby_24h": false,
      "all_inclusive": false,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "3+ anos, famílias que aceitam estrada longa por parque aquático",
      "family_score": 8.0,
      "family_notes": "Boa opção quando a prioridade é parque aquático, piscinas quentes e entretenimento, mas a logística pesa mais para bebês.",
      "main_strength": "Fonte oficial informa acesso ao Hot Beach Olímpia, quartos família, recreação infantil, brinquedoteca, playground e complexo aquático de águas termais.",
      "attention_point": "A distância da capital exige pausas; não tratar como primeira recomendação para bebê pequeno sem família acostumada a estrada longa.",
      "source_urls": ["https://hotbeach.com.br/hot-beach-resort/"],
      "source_highlights": [
        "Fonte oficial informa acesso gratuito ao parque para hóspedes.",
        "Fonte oficial cita brinquedoteca, recreação infantil e playground.",
        "Fonte oficial informa piscinas de águas quentes e quartos família."
      ],
      "confidence_level": "high",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "foz-do-iguacu",
      "slug": "wish-foz-do-iguacu",
      "name": "Wish Foz do Iguaçu Resort",
      "property_type": "resort",
      "price_tier": "upscale",
      "official_site_url": "https://www.grupowish.com/wish-foz-do-iguacu/entretenimento",
      "origin_focus": "São Paulo com voo para Foz do Iguaçu",
      "departure_mode": "voo",
      "drive_time_from_sao_paulo_minutes": null,
      "recommended_airport": "Congonhas ou Guarulhos para Foz do Iguaçu",
      "transfer_minutes": 20,
      "direct_flight_from_sao_paulo": true,
      "has_crib": null,
      "has_kids_club": true,
      "has_kids_pool": null,
      "has_heated_pool": true,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": null,
      "has_copa_baby": false,
      "has_copa_baby_24h": false,
      "all_inclusive": false,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "3+ anos, famílias que querem voo curto e passeios de natureza",
      "family_score": 8.4,
      "family_notes": "Boa combinação de voo curto, traslado simples e estrutura de resort, especialmente para crianças que já aproveitam atividades.",
      "main_strength": "A página oficial de entretenimento cita piscina aquecida, salão de jogos, Kids Club, trilha ecológica e recreação.",
      "attention_point": "Cataratas e passeios exigem controle de calor, carrinho e ritmo; crianças menores de 5 anos precisam de responsável no Kids Club.",
      "source_urls": ["https://www.grupowish.com/wish-foz-do-iguacu/entretenimento"],
      "source_highlights": [
        "Fonte oficial cita piscina aquecida diariamente.",
        "Fonte oficial descreve Kids Club com brinquedos, cinema, videogames e recreação.",
        "Fonte oficial informa que menores de 5 anos precisam estar acompanhados."
      ],
      "confidence_level": "verified",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "foz-do-iguacu",
      "slug": "recanto-cataratas-resort",
      "name": "Recanto Cataratas Thermas Resort & Convention",
      "property_type": "resort",
      "price_tier": "upscale",
      "official_site_url": "https://www.recantocataratasresort.com.br/",
      "origin_focus": "São Paulo com voo para Foz do Iguaçu",
      "departure_mode": "voo",
      "drive_time_from_sao_paulo_minutes": null,
      "recommended_airport": "Congonhas ou Guarulhos para Foz do Iguaçu",
      "transfer_minutes": 20,
      "direct_flight_from_sao_paulo": true,
      "has_crib": null,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": true,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": null,
      "has_copa_baby": false,
      "has_copa_baby_24h": false,
      "all_inclusive": false,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "3+ anos, famílias que valorizam piscina térmica e plano B indoor",
      "family_score": 8.2,
      "family_notes": "Boa alternativa em Foz para famílias que querem resort com lazer interno e piscina aquecida depois dos passeios.",
      "main_strength": "O site oficial destaca piscinas termais, piscina aquecida indoor, parque aquático para pequenos, boliche, fliperama e recreação.",
      "attention_point": "Confirmar política de berço, alimentação infantil e horários de recreação; os passeios externos seguem exigindo planejamento.",
      "source_urls": ["https://www.recantocataratasresort.com.br/"],
      "source_highlights": [
        "Fonte oficial cita piscinas termais e aquecidas indoor.",
        "Fonte oficial cita parque aquático para os pequenos.",
        "Fonte oficial apresenta boliche, fliperama e recreação como plano B."
      ],
      "confidence_level": "verified",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "gramado",
      "slug": "hotel-alpestre-gramado",
      "name": "Hotel Alpestre Gramado",
      "property_type": "hotel",
      "price_tier": "upscale",
      "official_site_url": "https://www.hotelalpestre.com.br/o-hotel/viagem-em-familia",
      "origin_focus": "São Paulo com voo para Porto Alegre ou Caxias do Sul",
      "departure_mode": "voo",
      "drive_time_from_sao_paulo_minutes": null,
      "recommended_airport": "Porto Alegre ou Caxias do Sul",
      "transfer_minutes": 120,
      "direct_flight_from_sao_paulo": true,
      "has_crib": true,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": true,
      "has_pool": true,
      "babysitting_available": true,
      "baby_meals_available": true,
      "has_copa_baby": true,
      "has_copa_baby_24h": true,
      "all_inclusive": false,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "bebês e crianças pequenas, com atenção ao traslado e ao frio",
      "family_score": 8.7,
      "family_notes": "Um dos hotéis mais fortes para bebê em Gramado pela clareza da estrutura: copa baby 24h, Baby Concierge e cardápio kids/baby.",
      "main_strength": "A página oficial informa copa baby 24h equipada, Baby Concierge com itens para empréstimo/locação, cardápio Kids e Baby e recreação.",
      "attention_point": "A logística até Gramado pode ser longa; evitar chegada tarde e checar clima, trânsito e traslado antes da compra.",
      "source_urls": [
        "https://www.hotelalpestre.com.br/o-hotel/viagem-em-familia",
        "https://www.hotelalpestre.com.br/facilidades-e-servicos-para-quem-viaja-com-bebes-temos-aqui-no-hotel-alpestre-em-gramado"
      ],
      "source_highlights": [
        "Fonte oficial cita Copa baby aberta 24h.",
        "Fonte oficial cita Baby Concierge com itens para bebês e crianças.",
        "Fonte oficial cita cardápio Kids e Baby."
      ],
      "confidence_level": "verified",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "gramado",
      "slug": "wish-serrano-gramado",
      "name": "Wish Serrano Resort",
      "property_type": "resort",
      "price_tier": "upscale",
      "official_site_url": "https://www.grupowish.com/wish-serrano",
      "origin_focus": "São Paulo com voo para Porto Alegre ou Caxias do Sul",
      "departure_mode": "voo",
      "drive_time_from_sao_paulo_minutes": null,
      "recommended_airport": "Porto Alegre ou Caxias do Sul",
      "transfer_minutes": 120,
      "direct_flight_from_sao_paulo": true,
      "has_crib": null,
      "has_kids_club": true,
      "has_kids_pool": null,
      "has_heated_pool": true,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": null,
      "has_copa_baby": false,
      "has_copa_baby_24h": false,
      "all_inclusive": false,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "3+ anos, famílias que querem localização central e lazer indoor",
      "family_score": 8.0,
      "family_notes": "Boa opção urbana em Gramado, com lazer infantil e piscina coberta aquecida, mas menos explícita para bebês que o Hotel Alpestre.",
      "main_strength": "A página oficial destaca piscina coberta aquecida a 32 °C, Kids Club, programação infantil e localização próxima ao centro.",
      "attention_point": "Para bebê pequeno, confirmar berço, copa baby e itens de apoio; em alta temporada, controlar lotação e deslocamentos.",
      "source_urls": ["https://www.grupowish.com/wish-serrano"],
      "source_highlights": [
        "Fonte oficial cita Kids Club e atividades infantis.",
        "Fonte oficial cita piscina coberta e aquecida a 32 °C.",
        "Fonte oficial destaca localização próxima ao centro de Gramado."
      ],
      "confidence_level": "high",
      "last_verified_at": "2026-06-05"
    }
  ]
  $json$::jsonb) as v(
    dest_slug text,
    slug text,
    name text,
    property_type text,
    price_tier text,
    official_site_url text,
    origin_focus text,
    departure_mode text,
    drive_time_from_sao_paulo_minutes int,
    recommended_airport text,
    transfer_minutes int,
    direct_flight_from_sao_paulo boolean,
    has_crib boolean,
    has_kids_club boolean,
    has_kids_pool boolean,
    has_heated_pool boolean,
    has_pool boolean,
    babysitting_available boolean,
    baby_meals_available boolean,
    has_copa_baby boolean,
    has_copa_baby_24h boolean,
    all_inclusive boolean,
    calm_beach boolean,
    recreation_available boolean,
    works_on_rainy_day boolean,
    min_child_age_months int,
    ideal_age text,
    family_score numeric,
    family_notes text,
    main_strength text,
    attention_point text,
    source_urls text[],
    source_highlights text[],
    confidence_level text,
    last_verified_at date
  )
)
insert into public.accommodations (
  destination_id,
  slug,
  name,
  property_type,
  price_tier,
  official_site_url,
  origin_focus,
  departure_mode,
  drive_time_from_sao_paulo_minutes,
  recommended_airport,
  transfer_minutes,
  direct_flight_from_sao_paulo,
  has_crib,
  has_kids_club,
  has_kids_pool,
  has_heated_pool,
  has_pool,
  babysitting_available,
  baby_meals_available,
  has_copa_baby,
  has_copa_baby_24h,
  all_inclusive,
  calm_beach,
  recreation_available,
  works_on_rainy_day,
  min_child_age_months,
  ideal_age,
  family_score,
  family_notes,
  main_strength,
  attention_point,
  source_urls,
  source_highlights,
  confidence_level,
  is_placeholder,
  last_verified_at
)
select
  d.id,
  v.slug,
  v.name,
  v.property_type,
  v.price_tier,
  v.official_site_url,
  v.origin_focus,
  v.departure_mode,
  v.drive_time_from_sao_paulo_minutes,
  v.recommended_airport,
  v.transfer_minutes,
  v.direct_flight_from_sao_paulo,
  v.has_crib,
  v.has_kids_club,
  v.has_kids_pool,
  v.has_heated_pool,
  v.has_pool,
  v.babysitting_available,
  v.baby_meals_available,
  v.has_copa_baby,
  v.has_copa_baby_24h,
  v.all_inclusive,
  v.calm_beach,
  v.recreation_available,
  v.works_on_rainy_day,
  v.min_child_age_months,
  v.ideal_age,
  v.family_score,
  v.family_notes,
  v.main_strength,
  v.attention_point,
  v.source_urls,
  v.source_highlights,
  v.confidence_level,
  false,
  v.last_verified_at
from hotel_rows v
join public.destinations d on d.slug = v.dest_slug
on conflict (slug) do update set
  destination_id = excluded.destination_id,
  name = excluded.name,
  property_type = excluded.property_type,
  price_tier = excluded.price_tier,
  official_site_url = excluded.official_site_url,
  origin_focus = excluded.origin_focus,
  departure_mode = excluded.departure_mode,
  drive_time_from_sao_paulo_minutes = excluded.drive_time_from_sao_paulo_minutes,
  recommended_airport = excluded.recommended_airport,
  transfer_minutes = excluded.transfer_minutes,
  direct_flight_from_sao_paulo = excluded.direct_flight_from_sao_paulo,
  has_crib = excluded.has_crib,
  has_kids_club = excluded.has_kids_club,
  has_kids_pool = excluded.has_kids_pool,
  has_heated_pool = excluded.has_heated_pool,
  has_pool = excluded.has_pool,
  babysitting_available = excluded.babysitting_available,
  baby_meals_available = excluded.baby_meals_available,
  has_copa_baby = excluded.has_copa_baby,
  has_copa_baby_24h = excluded.has_copa_baby_24h,
  all_inclusive = excluded.all_inclusive,
  calm_beach = excluded.calm_beach,
  recreation_available = excluded.recreation_available,
  works_on_rainy_day = excluded.works_on_rainy_day,
  min_child_age_months = excluded.min_child_age_months,
  ideal_age = excluded.ideal_age,
  family_score = excluded.family_score,
  family_notes = excluded.family_notes,
  main_strength = excluded.main_strength,
  attention_point = excluded.attention_point,
  source_urls = excluded.source_urls,
  source_highlights = excluded.source_highlights,
  confidence_level = excluded.confidence_level,
  is_placeholder = false,
  last_verified_at = excluded.last_verified_at,
  updated_at = now();

commit;
