begin;

with hotel_rows as (
  select *
  from jsonb_to_recordset($json$
  [
    {
      "dest_slug": "hotel-fazenda-sp",
      "slug": "clara-dourado-resort",
      "name": "Clara Dourado Resort",
      "property_type": "resort",
      "price_tier": "luxury",
      "official_site_url": "https://clararesorts.com.br/nossos-resorts/clara-dourado/acomodacoes/chale-master/",
      "origin_focus": "Capital de Sao Paulo",
      "departure_mode": "carro",
      "drive_time_from_sao_paulo_minutes": 210,
      "recommended_airport": null,
      "transfer_minutes": null,
      "direct_flight_from_sao_paulo": false,
      "has_crib": true,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": true,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": true,
      "has_copa_baby": true,
      "has_copa_baby_24h": null,
      "all_inclusive": false,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "bebes e criancas pequenas, com familia acostumada a estrada de 3h+",
      "family_score": 8.8,
      "family_notes": "Hotel de campo muito forte para familias com bebes pela combinacao de bercos, banheira, carrinho, papinhas, copinhas e piscinas aquecidas.",
      "main_strength": "A fonte oficial cita berco, banheira, carrinho para criancas menores de 2 anos, papinhas, copinhas do bebe, piscina aquecida, brinquedoteca e playground.",
      "attention_point": "A estrada e a distancia tornam melhor para familias que ja toleram deslocamentos mais longos com bebe.",
      "source_urls": ["https://clararesorts.com.br/nossos-resorts/clara-dourado/acomodacoes/chale-master/"],
      "source_highlights": [
        "Fonte oficial cita berco, banheira, carrinho e papinhas.",
        "Fonte oficial cita copinhas do bebe nos corredores.",
        "Fonte oficial lista piscina aquecida, piscina infantil, brinquedoteca e playground."
      ],
      "confidence_level": "verified",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "campos-do-jordao",
      "slug": "toriba-campos-do-jordao",
      "name": "Hotel Toriba",
      "property_type": "hotel",
      "price_tier": "luxury",
      "official_site_url": "https://www.toriba.com.br/",
      "origin_focus": "Capital de Sao Paulo",
      "departure_mode": "carro",
      "drive_time_from_sao_paulo_minutes": 180,
      "recommended_airport": null,
      "transfer_minutes": null,
      "direct_flight_from_sao_paulo": false,
      "has_crib": null,
      "has_kids_club": true,
      "has_kids_pool": null,
      "has_heated_pool": null,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": null,
      "has_copa_baby": false,
      "has_copa_baby_24h": false,
      "all_inclusive": false,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "2+ anos, familias que querem serra com estrutura de hotel classico",
      "family_score": 7.8,
      "family_notes": "Boa opcao para Campos quando a familia quer hotel tradicional, natureza e lazer, mas exige atencao ao frio e a lotacao de temporada.",
      "main_strength": "O site oficial posiciona o Toriba como hotel reconhecido para criancas, com lazer e entretenimento em estrutura de resort.",
      "attention_point": "Confirmar berco, itens para bebe e programacao infantil antes da reserva, especialmente fora de feriados e ferias.",
      "source_urls": ["https://www.toriba.com.br/"],
      "source_highlights": [
        "Fonte oficial descreve lazer e entretenimento e diz ser reconhecido como hotel para criancas.",
        "Fonte oficial informa grande area de mata nativa e trilhas.",
        "Boa opcao para roteiro de serra com criancas acima de 2 anos."
      ],
      "confidence_level": "high",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "sao-roque",
      "slug": "villa-rossa-sao-roque",
      "name": "Hotel Villa Rossa",
      "property_type": "resort",
      "price_tier": "upscale",
      "official_site_url": "https://www.villarossa.com.br/",
      "origin_focus": "Capital de Sao Paulo",
      "departure_mode": "carro",
      "drive_time_from_sao_paulo_minutes": 60,
      "recommended_airport": null,
      "transfer_minutes": null,
      "direct_flight_from_sao_paulo": false,
      "has_crib": null,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": true,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": null,
      "has_copa_baby": false,
      "has_copa_baby_24h": false,
      "all_inclusive": false,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": 48,
      "ideal_age": "4+ anos, familias que querem natureza perto de Sao Paulo",
      "family_score": 8.1,
      "family_notes": "Otimo encaixe para fim de semana curto perto da capital, principalmente para criancas a partir de 4 anos.",
      "main_strength": "A fonte oficial cita pensao completa, lazer amplo, monitoria para criancas a partir de 4 anos, piscina coberta com jacuzzi e complexo aquatico.",
      "attention_point": "Menores de 4 anos nao sao o publico principal da monitoria; confirmar berco e apoio de bebe antes de reservar.",
      "source_urls": ["https://www.villarossa.com.br/", "https://www.villarossa.com.br/lazer", "https://www.villarossa.com.br/faq"],
      "source_highlights": [
        "Fonte oficial informa monitoria para criancas a partir de 4 anos.",
        "Fonte oficial cita piscina coberta com jacuzzi e complexo aquatico.",
        "Fonte oficial destaca pensao completa e distancia de cerca de 50 km de Sao Paulo."
      ],
      "confidence_level": "verified",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "litoral-norte-sp",
      "slug": "casa-grande-guaruja",
      "name": "Casa Grande Hotel Resort & Spa",
      "property_type": "resort",
      "price_tier": "luxury",
      "official_site_url": "https://casagrandehotelresort.com.br/",
      "origin_focus": "Capital de Sao Paulo",
      "departure_mode": "carro",
      "drive_time_from_sao_paulo_minutes": 100,
      "recommended_airport": null,
      "transfer_minutes": null,
      "direct_flight_from_sao_paulo": false,
      "has_crib": null,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": true,
      "has_pool": true,
      "babysitting_available": true,
      "baby_meals_available": null,
      "has_copa_baby": null,
      "has_copa_baby_24h": null,
      "all_inclusive": false,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "2+ anos, familias que querem praia com resort e plano B infantil",
      "family_score": 8.2,
      "family_notes": "Boa alternativa de praia perto de Sao Paulo com estrutura infantil robusta, embora Guaruja exija cautela com transito e mar.",
      "main_strength": "O site oficial destaca Parque da Crianca, experiencias familiares e localizacao na Praia da Enseada; fonte oficial de estrutura cita piscinas infantis, brinquedos, monitoria e baby-sitter.",
      "attention_point": "Checar transito da serra, condicoes do mar e se a rotina de praia combina com a idade da crianca.",
      "source_urls": ["https://casagrandehotelresort.com.br/", "https://homolog.tavaresdev.net/estrutura/"],
      "source_highlights": [
        "Fonte oficial lista Parque da Crianca e experiencias familiares.",
        "Fonte oficial de estrutura cita piscinas infantis, sala de jogos, brinquedos e playground.",
        "Fonte oficial de estrutura informa servico de baby-sitter mediante solicitacao."
      ],
      "confidence_level": "high",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "beto-carrero-penha",
      "slug": "vila-olaria-penha",
      "name": "Vila Olaria Hotel",
      "property_type": "hotel",
      "price_tier": "mid",
      "official_site_url": "https://www.betocarrero.com.br/pt/hoteis/vila-olaria-hotel-penha",
      "origin_focus": "Sao Paulo com voo para Navegantes",
      "departure_mode": "voo",
      "drive_time_from_sao_paulo_minutes": null,
      "recommended_airport": "Navegantes",
      "transfer_minutes": 25,
      "direct_flight_from_sao_paulo": true,
      "has_crib": null,
      "has_kids_club": true,
      "has_kids_pool": true,
      "has_heated_pool": false,
      "has_pool": true,
      "babysitting_available": null,
      "baby_meals_available": null,
      "has_copa_baby": false,
      "has_copa_baby_24h": false,
      "all_inclusive": false,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "4+ anos, familias com foco em parque tematico",
      "family_score": 7.7,
      "family_notes": "Hotel de apoio pratico para Beto Carrero, com estrutura infantil e localizacao muito conveniente para reduzir deslocamentos.",
      "main_strength": "A pagina oficial do Beto Carrero informa que o hotel foi estruturado para familias, com brinquedoteca, playground, cantinho do bebe, piscina, sala de jogos e quadra.",
      "attention_point": "Nao confundir com resort de descanso; e uma base funcional para parque, melhor para criancas que ja aproveitam dia intenso.",
      "source_urls": ["https://www.betocarrero.com.br/pt/hoteis/vila-olaria-hotel-penha"],
      "source_highlights": [
        "Fonte oficial informa brinquedoteca, playground e cantinho do bebe.",
        "Fonte oficial cita piscina adulto e infantil e sala de jogos.",
        "Fonte oficial posiciona o hotel ao lado do Beto Carrero World."
      ],
      "confidence_level": "verified",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "buenos-aires",
      "slug": "bulnes-eco-suites-buenos-aires",
      "name": "Bulnes Eco Suites",
      "property_type": "apart-hotel",
      "price_tier": "mid",
      "official_site_url": "https://bulnesecosuites.com/index.php",
      "origin_focus": "Sao Paulo com voo para Buenos Aires",
      "departure_mode": "voo internacional leve",
      "drive_time_from_sao_paulo_minutes": null,
      "recommended_airport": "Guarulhos para Buenos Aires",
      "transfer_minutes": 45,
      "direct_flight_from_sao_paulo": true,
      "has_crib": null,
      "has_kids_club": false,
      "has_kids_pool": false,
      "has_heated_pool": false,
      "has_pool": false,
      "has_kitchenette": true,
      "babysitting_available": null,
      "baby_meals_available": false,
      "has_copa_baby": false,
      "has_copa_baby_24h": false,
      "all_inclusive": false,
      "calm_beach": false,
      "recreation_available": false,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "3+ anos, primeira viagem internacional urbana com rotina flexivel",
      "family_score": 7.0,
      "family_notes": "Nao e hotel infantil, mas funciona como base urbana com kitchenette em Palermo para familias que precisam preparar lanches e manter rotina.",
      "main_strength": "A fonte oficial informa apart hotel em Palermo com kitchenette, micro-ondas, chaleira e frigobar sob mesa.",
      "attention_point": "Confirmar berco diretamente e evitar vender como hotel kids; e uma base logistica para cidade.",
      "source_urls": ["https://bulnesecosuites.com/index.php"],
      "source_highlights": [
        "Fonte oficial informa kitchenette com micro-ondas, chaleira e frigobar.",
        "Localizacao em Palermo facilita deslocamentos urbanos com familia.",
        "Melhor para criancas maiores que toleram roteiro de cidade."
      ],
      "confidence_level": "high",
      "last_verified_at": "2026-06-05"
    },
    {
      "dest_slug": "orlando",
      "slug": "disney-art-of-animation-resort",
      "name": "Disney's Art of Animation Resort",
      "property_type": "resort",
      "price_tier": "upscale",
      "official_site_url": "https://www.disneyworld.co.uk/en_GB/resort-hotels-benefits/",
      "origin_focus": "Sao Paulo com voo para Orlando",
      "departure_mode": "voo internacional",
      "drive_time_from_sao_paulo_minutes": null,
      "recommended_airport": "Guarulhos para Orlando",
      "transfer_minutes": 30,
      "direct_flight_from_sao_paulo": true,
      "has_crib": true,
      "has_kids_club": false,
      "has_kids_pool": true,
      "has_heated_pool": null,
      "has_pool": true,
      "has_kitchenette": true,
      "babysitting_available": null,
      "baby_meals_available": false,
      "has_copa_baby": false,
      "has_copa_baby_24h": false,
      "all_inclusive": false,
      "calm_beach": false,
      "recreation_available": true,
      "works_on_rainy_day": true,
      "min_child_age_months": null,
      "ideal_age": "5+ anos, familias que querem imersao Disney e suites para rotina de parque",
      "family_score": 7.6,
      "family_notes": "Boa base para familias em Orlando pelas Family Suites, mas a viagem e longa e intensa para bebes pequenos.",
      "main_strength": "Fonte oficial Disney informa Family Suites tematicas para ate 6 hospedes; materiais oficiais de resort indicam opcoes com kitchenette e berco para crianca pequena.",
      "attention_point": "Nao e recomendacao simples para bebe: considerar voo longo, fuso, custo, calor e necessidade de pausas.",
      "source_urls": [
        "https://www.disneyworld.co.uk/en_GB/resort-hotels-benefits/",
        "https://media.disneywebcontent.com/StaticFiles/DTA-Domestic/pdf/ResortOverview/GrandFloridian.pdf"
      ],
      "source_highlights": [
        "Fonte oficial Disney informa Family Suites tematicas e espaco para ate 6 hospedes.",
        "Fonte oficial Disney descreve studios/suites com kitchenette em resorts selecionados.",
        "Melhor para criancas maiores que conseguem aproveitar parques e rotina intensa."
      ],
      "confidence_level": "high",
      "last_verified_at": "2026-06-05"
    }
  ]
  $json$::jsonb) as v(
    dest_slug text,
    slug text,
    name text,
    property_type text,
    price_tier text,
    official_site_url text,
    origin_focus text,
    departure_mode text,
    drive_time_from_sao_paulo_minutes int,
    recommended_airport text,
    transfer_minutes int,
    direct_flight_from_sao_paulo boolean,
    has_crib boolean,
    has_kids_club boolean,
    has_kids_pool boolean,
    has_heated_pool boolean,
    has_pool boolean,
    has_kitchenette boolean,
    babysitting_available boolean,
    baby_meals_available boolean,
    has_copa_baby boolean,
    has_copa_baby_24h boolean,
    all_inclusive boolean,
    calm_beach boolean,
    recreation_available boolean,
    works_on_rainy_day boolean,
    min_child_age_months int,
    ideal_age text,
    family_score numeric,
    family_notes text,
    main_strength text,
    attention_point text,
    source_urls text[],
    source_highlights text[],
    confidence_level text,
    last_verified_at date
  )
)
insert into public.accommodations (
  destination_id,
  slug,
  name,
  property_type,
  price_tier,
  official_site_url,
  origin_focus,
  departure_mode,
  drive_time_from_sao_paulo_minutes,
  recommended_airport,
  transfer_minutes,
  direct_flight_from_sao_paulo,
  has_crib,
  has_kids_club,
  has_kids_pool,
  has_heated_pool,
  has_pool,
  has_kitchenette,
  babysitting_available,
  baby_meals_available,
  has_copa_baby,
  has_copa_baby_24h,
  all_inclusive,
  calm_beach,
  recreation_available,
  works_on_rainy_day,
  min_child_age_months,
  ideal_age,
  family_score,
  family_notes,
  main_strength,
  attention_point,
  source_urls,
  source_highlights,
  confidence_level,
  is_placeholder,
  last_verified_at
)
select
  d.id,
  v.slug,
  v.name,
  v.property_type,
  v.price_tier,
  v.official_site_url,
  v.origin_focus,
  v.departure_mode,
  v.drive_time_from_sao_paulo_minutes,
  v.recommended_airport,
  v.transfer_minutes,
  v.direct_flight_from_sao_paulo,
  v.has_crib,
  v.has_kids_club,
  v.has_kids_pool,
  v.has_heated_pool,
  v.has_pool,
  v.has_kitchenette,
  v.babysitting_available,
  v.baby_meals_available,
  v.has_copa_baby,
  v.has_copa_baby_24h,
  v.all_inclusive,
  v.calm_beach,
  v.recreation_available,
  v.works_on_rainy_day,
  v.min_child_age_months,
  v.ideal_age,
  v.family_score,
  v.family_notes,
  v.main_strength,
  v.attention_point,
  v.source_urls,
  v.source_highlights,
  v.confidence_level,
  false,
  v.last_verified_at
from hotel_rows v
join public.destinations d on d.slug = v.dest_slug
on conflict (slug) do update set
  destination_id = excluded.destination_id,
  name = excluded.name,
  property_type = excluded.property_type,
  price_tier = excluded.price_tier,
  official_site_url = excluded.official_site_url,
  origin_focus = excluded.origin_focus,
  departure_mode = excluded.departure_mode,
  drive_time_from_sao_paulo_minutes = excluded.drive_time_from_sao_paulo_minutes,
  recommended_airport = excluded.recommended_airport,
  transfer_minutes = excluded.transfer_minutes,
  direct_flight_from_sao_paulo = excluded.direct_flight_from_sao_paulo,
  has_crib = excluded.has_crib,
  has_kids_club = excluded.has_kids_club,
  has_kids_pool = excluded.has_kids_pool,
  has_heated_pool = excluded.has_heated_pool,
  has_pool = excluded.has_pool,
  has_kitchenette = excluded.has_kitchenette,
  babysitting_available = excluded.babysitting_available,
  baby_meals_available = excluded.baby_meals_available,
  has_copa_baby = excluded.has_copa_baby,
  has_copa_baby_24h = excluded.has_copa_baby_24h,
  all_inclusive = excluded.all_inclusive,
  calm_beach = excluded.calm_beach,
  recreation_available = excluded.recreation_available,
  works_on_rainy_day = excluded.works_on_rainy_day,
  min_child_age_months = excluded.min_child_age_months,
  ideal_age = excluded.ideal_age,
  family_score = excluded.family_score,
  family_notes = excluded.family_notes,
  main_strength = excluded.main_strength,
  attention_point = excluded.attention_point,
  source_urls = excluded.source_urls,
  source_highlights = excluded.source_highlights,
  confidence_level = excluded.confidence_level,
  is_placeholder = false,
  last_verified_at = excluded.last_verified_at,
  updated_at = now();

commit;
