begin;

with image_rows as (
  select *
  from jsonb_to_recordset($json$
[
  {
    "destination_slug": "resort-interior-sp",
    "destination_name": "Campinas",
    "city": "Campinas",
    "state": "Sao Paulo",
    "country": "Brasil",
    "category": "resort",
    "context": "family travel",
    "query_used": "Campinas Brasil",
    "image_url": "https://images.pexels.com/photos/13244659/pexels-photo-13244659.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "thumbnail_url": "https://images.pexels.com/photos/13244659/pexels-photo-13244659.jpeg?auto=compress&cs=tinysrgb&h=350",
    "source": "pexels",
    "author_name": "Nicholas Shirazawa",
    "author_url": "https://www.pexels.com/pt-br/@nicholas-shirazawa-286674048",
    "original_url": "https://www.pexels.com/pt-br/foto/cidade-meio-urbano-arranha-ceus-arranha-ceu-13244659/",
    "license": "Pexels License",
    "attribution_required": false,
    "attribution_text": "Foto por Nicholas Shirazawa via Pexels",
    "width": 6000,
    "height": 4000,
    "alt": "Foto profissional grátis de ambiente urbano, América do Sul, ao ar livre",
    "confidence_score": 95,
    "status": "auto_approved"
  },
  {
    "destination_slug": "atibaia",
    "destination_name": "Atibaia",
    "city": "Atibaia",
    "state": "Sao Paulo",
    "country": "Brasil",
    "category": "natureza",
    "context": "family travel",
    "query_used": "Atibaia Brasil",
    "image_url": "https://images.pexels.com/photos/30991750/pexels-photo-30991750.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "thumbnail_url": "https://images.pexels.com/photos/30991750/pexels-photo-30991750.jpeg?auto=compress&cs=tinysrgb&h=350",
    "source": "pexels",
    "author_name": "Eudes cs",
    "author_url": "https://www.pexels.com/pt-br/@eudescs",
    "original_url": "https://www.pexels.com/pt-br/foto/paisagem-urbana-com-bandeira-brasileira-e-predios-30991750/",
    "license": "Pexels License",
    "attribution_required": false,
    "attribution_text": "Foto por Eudes cs via Pexels",
    "width": 6000,
    "height": 4000,
    "alt": "Uma vista urbana vibrante exibindo edifícios e uma proeminente bandeira brasileira em meio a uma vegetação exuberante.",
    "confidence_score": 95,
    "status": "auto_approved"
  },
  {
    "destination_slug": "hotel-fazenda-sp",
    "destination_name": "Dourado",
    "city": "Dourado",
    "state": "Sao Paulo",
    "country": "Brasil",
    "category": "campo",
    "context": "family travel",
    "query_used": "Dourado Brasil",
    "image_url": "https://images.pexels.com/photos/8533896/pexels-photo-8533896.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "thumbnail_url": "https://images.pexels.com/photos/8533896/pexels-photo-8533896.jpeg?auto=compress&cs=tinysrgb&h=350",
    "source": "pexels",
    "author_name": "Matheus Bertelli",
    "author_url": "https://www.pexels.com/pt-br/@bertellifotografia",
    "original_url": "https://www.pexels.com/pt-br/foto/natureza-nascer-do-sol-ao-ar-livre-outdoors-8533896/",
    "license": "Pexels License",
    "attribution_required": false,
    "attribution_text": "Foto por Matheus Bertelli via Pexels",
    "width": 10289,
    "height": 6739,
    "alt": "Foto profissional grátis de América do Sul, ao ar livre, aventura",
    "confidence_score": 95,
    "status": "auto_approved"
  },
  {
    "destination_slug": "campos-do-jordao",
    "destination_name": "Campos do Jordao",
    "city": "Campos do Jordao",
    "state": "Sao Paulo",
    "country": "Brasil",
    "category": "montanha",
    "context": "family travel",
    "query_used": "Campos do Jordao Brasil",
    "image_url": "https://images.pexels.com/photos/18030380/pexels-photo-18030380.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "thumbnail_url": "https://images.pexels.com/photos/18030380/pexels-photo-18030380.jpeg?auto=compress&cs=tinysrgb&h=350",
    "source": "pexels",
    "author_name": "Manoel  Junior",
    "author_url": "https://www.pexels.com/pt-br/@manoel-junior-664863191",
    "original_url": "https://www.pexels.com/pt-br/foto/panorama-vista-paisagem-montanhas-18030380/",
    "license": "Pexels License",
    "attribution_required": false,
    "attribution_text": "Foto por Manoel  Junior via Pexels",
    "width": 6000,
    "height": 4000,
    "alt": "Foto profissional grátis de aldeia, América do Sul, ao ar livre",
    "confidence_score": 95,
    "status": "auto_approved"
  },
  {
    "destination_slug": "sao-roque",
    "destination_name": "Sao Roque",
    "city": "Sao Roque",
    "state": "Sao Paulo",
    "country": "Brasil",
    "category": "natureza",
    "context": "family travel",
    "query_used": "Sao Roque Brasil",
    "image_url": "https://images.pexels.com/photos/13870421/pexels-photo-13870421.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "thumbnail_url": "https://images.pexels.com/photos/13870421/pexels-photo-13870421.jpeg?auto=compress&cs=tinysrgb&h=350",
    "source": "pexels",
    "author_name": "Matheus Bertelli",
    "author_url": "https://www.pexels.com/pt-br/@bertellifotografia",
    "original_url": "https://www.pexels.com/pt-br/foto/montanhas-colinas-montes-horizonte-13870421/",
    "license": "Pexels License",
    "attribution_required": false,
    "attribution_text": "Foto por Matheus Bertelli via Pexels",
    "width": 8192,
    "height": 3052,
    "alt": "Foto profissional grátis de agricultura, América do Sul, ao ar livre",
    "confidence_score": 95,
    "status": "auto_approved"
  },
  {
    "destination_slug": "olimpia",
    "destination_name": "Olimpia",
    "city": "Olimpia",
    "state": "Sao Paulo",
    "country": "Brasil",
    "category": "parque aquatico",
    "context": "family travel",
    "query_used": "Olimpia Brasil",
    "image_url": "https://images.pexels.com/photos/30991750/pexels-photo-30991750.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "thumbnail_url": "https://images.pexels.com/photos/30991750/pexels-photo-30991750.jpeg?auto=compress&cs=tinysrgb&h=350",
    "source": "pexels",
    "author_name": "Eudes cs",
    "author_url": "https://www.pexels.com/pt-br/@eudescs",
    "original_url": "https://www.pexels.com/pt-br/foto/paisagem-urbana-com-bandeira-brasileira-e-predios-30991750/",
    "license": "Pexels License",
    "attribution_required": false,
    "attribution_text": "Foto por Eudes cs via Pexels",
    "width": 6000,
    "height": 4000,
    "alt": "Uma vista urbana vibrante exibindo edifícios e uma proeminente bandeira brasileira em meio a uma vegetação exuberante.",
    "confidence_score": 95,
    "status": "pending_review"
  },
  {
    "destination_slug": "litoral-norte-sp",
    "destination_name": "Guaruja",
    "city": "Guaruja",
    "state": "Sao Paulo",
    "country": "Brasil",
    "category": "praia",
    "context": "family travel",
    "query_used": "Guaruja Brasil",
    "image_url": "https://images.pexels.com/photos/8291496/pexels-photo-8291496.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "thumbnail_url": "https://images.pexels.com/photos/8291496/pexels-photo-8291496.jpeg?auto=compress&cs=tinysrgb&h=350",
    "source": "pexels",
    "author_name": "Jeff Paulino",
    "author_url": "https://www.pexels.com/pt-br/@jeff-paulino-67502700",
    "original_url": "https://www.pexels.com/pt-br/foto/mar-praia-litoral-barco-8291496/",
    "license": "Pexels License",
    "attribution_required": false,
    "attribution_text": "Foto por Jeff Paulino via Pexels",
    "width": 6000,
    "height": 4000,
    "alt": "Foto profissional grátis de à beira-mar, água, América do Sul",
    "confidence_score": 95,
    "status": "auto_approved"
  },
  {
    "destination_slug": "praia-do-forte",
    "destination_name": "Praia do Forte",
    "city": "Mata de Sao Joao",
    "state": "Bahia",
    "country": "Brasil",
    "category": "praia",
    "context": "family travel",
    "query_used": "Praia do Forte Brasil",
    "image_url": "https://images.pexels.com/photos/6910147/pexels-photo-6910147.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "thumbnail_url": "https://images.pexels.com/photos/6910147/pexels-photo-6910147.jpeg?auto=compress&cs=tinysrgb&h=350",
    "source": "pexels",
    "author_name": "alexandre saraiva carniato",
    "author_url": "https://www.pexels.com/pt-br/@alexandre-saraiva-carniato-583650",
    "original_url": "https://www.pexels.com/pt-br/foto/natureza-praia-litoral-areia-6910147/",
    "license": "Pexels License",
    "attribution_required": false,
    "attribution_text": "Foto por alexandre saraiva carniato via Pexels",
    "width": 6148,
    "height": 4099,
    "alt": "Foto profissional grátis de América do Sul, ao ar livre, areia",
    "confidence_score": 80,
    "status": "auto_approved"
  },
  {
    "destination_slug": "porto-de-galinhas",
    "destination_name": "Porto de Galinhas",
    "city": "Ipojuca",
    "state": "Pernambuco",
    "country": "Brasil",
    "category": "praia",
    "context": "family travel",
    "query_used": "Porto de Galinhas Brasil",
    "image_url": "https://images.pexels.com/photos/9494150/pexels-photo-9494150.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "thumbnail_url": "https://images.pexels.com/photos/9494150/pexels-photo-9494150.jpeg?auto=compress&cs=tinysrgb&h=350",
    "source": "pexels",
    "author_name": "Gabriel Galvao",
    "author_url": "https://www.pexels.com/pt-br/@gabriel-galvao-72544083",
    "original_url": "https://www.pexels.com/pt-br/foto/mar-praia-litoral-areia-9494150/",
    "license": "Pexels License",
    "attribution_required": false,
    "attribution_text": "Foto por Gabriel Galvao via Pexels",
    "width": 7087,
    "height": 3986,
    "alt": "Foto profissional grátis de à beira-mar, América do Sul, américa latina",
    "confidence_score": 75,
    "status": "auto_approved"
  },
  {
    "destination_slug": "maceio-maragogi",
    "destination_name": "Maragogi",
    "city": "Maragogi",
    "state": "Alagoas",
    "country": "Brasil",
    "category": "praia",
    "context": "family travel",
    "query_used": "Maragogi Brasil",
    "image_url": "https://images.pexels.com/photos/18149722/pexels-photo-18149722.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "thumbnail_url": "https://images.pexels.com/photos/18149722/pexels-photo-18149722.jpeg?auto=compress&cs=tinysrgb&h=350",
    "source": "pexels",
    "author_name": "Nino Souza",
    "author_url": "https://www.pexels.com/pt-br/@ninosouza",
    "original_url": "https://www.pexels.com/pt-br/foto/mar-praia-litoral-costa-18149722/",
    "license": "Pexels License",
    "attribution_required": false,
    "attribution_text": "Foto por Nino Souza via Pexels",
    "width": 8000,
    "height": 6048,
    "alt": "Foto profissional grátis de à beira-mar, águas azul-turquesa, águas calmas",
    "confidence_score": 75,
    "status": "auto_approved"
  },
  {
    "destination_slug": "foz-do-iguacu",
    "destination_name": "Foz do Iguacu",
    "city": "Foz do Iguacu",
    "state": "Parana",
    "country": "Brasil",
    "category": "natureza",
    "context": "family travel",
    "query_used": "Foz do Iguacu Brasil",
    "image_url": "https://images.pexels.com/photos/26851095/pexels-photo-26851095.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "thumbnail_url": "https://images.pexels.com/photos/26851095/pexels-photo-26851095.jpeg?auto=compress&cs=tinysrgb&h=350",
    "source": "pexels",
    "author_name": "Pedro Lucas",
    "author_url": "https://www.pexels.com/pt-br/@pedro-lucas-269808503",
    "original_url": "https://www.pexels.com/pt-br/foto/natureza-rochas-pedras-musgo-26851095/",
    "license": "Pexels License",
    "attribution_required": false,
    "attribution_text": "Foto por Pedro Lucas via Pexels",
    "width": 5694,
    "height": 4270,
    "alt": "Foto profissional grátis de América do Sul, ao ar livre, arco-íris",
    "confidence_score": 95,
    "status": "auto_approved"
  },
  {
    "destination_slug": "gramado",
    "destination_name": "Gramado",
    "city": "Gramado",
    "state": "Rio Grande do Sul",
    "country": "Brasil",
    "category": "montanha",
    "context": "family travel",
    "query_used": "Gramado Brasil",
    "image_url": "https://images.pexels.com/photos/6628782/pexels-photo-6628782.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "thumbnail_url": "https://images.pexels.com/photos/6628782/pexels-photo-6628782.jpeg?auto=compress&cs=tinysrgb&h=350",
    "source": "pexels",
    "author_name": "Jean depocas",
    "author_url": "https://www.pexels.com/pt-br/@jean-depocas-1110767",
    "original_url": "https://www.pexels.com/pt-br/foto/panorama-vista-paisagem-natureza-6628782/",
    "license": "Pexels License",
    "attribution_required": false,
    "attribution_text": "Foto por Jean depocas via Pexels",
    "width": 6048,
    "height": 4011,
    "alt": "Foto profissional grátis de aerofotografia, ao ar livre, árvores verdes",
    "confidence_score": 95,
    "status": "auto_approved"
  },
  {
    "destination_slug": "beto-carrero-penha",
    "destination_name": "Penha",
    "city": "Penha",
    "state": "Santa Catarina",
    "country": "Brasil",
    "category": "parque",
    "context": "family travel",
    "query_used": "Penha family travel",
    "image_url": "https://images.pexels.com/photos/36827973/pexels-photo-36827973.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "thumbnail_url": "https://images.pexels.com/photos/36827973/pexels-photo-36827973.jpeg?auto=compress&cs=tinysrgb&h=350",
    "source": "pexels",
    "author_name": "Leandro Rossi",
    "author_url": "https://www.pexels.com/pt-br/@leandro-rossi-2151612851",
    "original_url": "https://www.pexels.com/pt-br/foto/detalhe-de-uma-poca-de-mare-e-formacao-rochosa-no-brasil-36827973/",
    "license": "Pexels License",
    "attribution_required": false,
    "attribution_text": "Foto por Leandro Rossi via Pexels",
    "width": 6000,
    "height": 4000,
    "alt": "Vista detalhada de uma poça de maré aninhada entre rochas escarpadas em Penha, Santa Catarina.",
    "confidence_score": 85,
    "status": "auto_approved"
  },
  {
    "destination_slug": "buenos-aires",
    "destination_name": "Buenos Aires",
    "city": "Buenos Aires",
    "state": "Buenos Aires",
    "country": "Argentina",
    "category": "cidade",
    "context": "family travel",
    "query_used": "Buenos Aires Argentina",
    "image_url": "https://images.pexels.com/photos/32996851/pexels-photo-32996851.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "thumbnail_url": "https://images.pexels.com/photos/32996851/pexels-photo-32996851.jpeg?auto=compress&cs=tinysrgb&h=350",
    "source": "pexels",
    "author_name": "Guillermo Berlin",
    "author_url": "https://www.pexels.com/pt-br/@guillermo-berlin-1524368912",
    "original_url": "https://www.pexels.com/pt-br/foto/32996851/",
    "license": "Pexels License",
    "attribution_required": false,
    "attribution_text": "Foto por Guillermo Berlin via Pexels",
    "width": 7008,
    "height": 4672,
    "alt": "Foto profissional grátis de @exterior, ambiente urbano, América do Sul",
    "confidence_score": 95,
    "status": "auto_approved"
  },
  {
    "destination_slug": "orlando",
    "destination_name": "Orlando",
    "city": "Orlando",
    "state": "Florida",
    "country": "Estados Unidos",
    "category": "parque",
    "context": "family travel",
    "query_used": "Orlando Estados Unidos",
    "image_url": "https://images.pexels.com/photos/34936498/pexels-photo-34936498.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "thumbnail_url": "https://images.pexels.com/photos/34936498/pexels-photo-34936498.jpeg?auto=compress&cs=tinysrgb&h=350",
    "source": "pexels",
    "author_name": "Simon Steiner",
    "author_url": "https://www.pexels.com/pt-br/@simon-steiner-1108932161",
    "original_url": "https://www.pexels.com/pt-br/foto/vista-panoramica-do-horizonte-de-orlando-a-partir-do-lago-eola-34936498/",
    "license": "Pexels License",
    "attribution_required": false,
    "attribution_text": "Foto por Simon Steiner via Pexels",
    "width": 10413,
    "height": 5857,
    "alt": "Vista deslumbrante do horizonte do centro de Orlando emoldurado pelas árvores do Lago Eola.",
    "confidence_score": 95,
    "status": "auto_approved"
  }
]
$json$) as row(
    destination_slug text,
    destination_name text,
    city text,
    state text,
    country text,
    category text,
    context text,
    query_used text,
    image_url text,
    thumbnail_url text,
    source text,
    author_name text,
    author_url text,
    original_url text,
    license text,
    attribution_required boolean,
    attribution_text text,
    width int,
    height int,
    alt text,
    confidence_score int,
    status text
  )
)
insert into public.destination_images (
  destination_slug,
  destination_name,
  city,
  state,
  country,
  category,
  context,
  query_used,
  image_url,
  thumbnail_url,
  source,
  author_name,
  author_url,
  original_url,
  license,
  attribution_required,
  attribution_text,
  width,
  height,
  alt,
  confidence_score,
  status
)
select
  destination_slug,
  destination_name,
  city,
  state,
  country,
  category,
  context,
  query_used,
  image_url,
  thumbnail_url,
  source,
  author_name,
  author_url,
  original_url,
  license,
  attribution_required,
  attribution_text,
  width,
  height,
  alt,
  confidence_score,
  status
from image_rows
on conflict (destination_slug, source) do update set
  destination_name = excluded.destination_name,
  city = excluded.city,
  state = excluded.state,
  country = excluded.country,
  category = excluded.category,
  context = excluded.context,
  query_used = excluded.query_used,
  image_url = excluded.image_url,
  thumbnail_url = excluded.thumbnail_url,
  author_name = excluded.author_name,
  author_url = excluded.author_url,
  original_url = excluded.original_url,
  license = excluded.license,
  attribution_required = excluded.attribution_required,
  attribution_text = excluded.attribution_text,
  width = excluded.width,
  height = excluded.height,
  alt = excluded.alt,
  confidence_score = excluded.confidence_score,
  status = excluded.status,
  updated_at = now();

commit;
