create table if not exists public.destination_family_hassle (
  destination_id uuid primary key references public.destinations(id) on delete cascade,
  family_hassle_level text not null default 'moderado'
    check (family_hassle_level in ('baixo', 'moderado', 'alto', 'muito_alto')),
  hassle_score integer not null default 42 check (hassle_score between 0 and 100),
  baby_friendliness_score integer not null default 58 check (baby_friendliness_score between 0 and 100),
  toddler_friendliness_score integer not null default 64 check (toddler_friendliness_score between 0 and 100),
  kids_6_10_friendliness_score integer not null default 72 check (kids_6_10_friendliness_score between 0 and 100),
  teen_friendliness_score integer not null default 70 check (teen_friendliness_score between 0 and 100),
  best_minimum_age integer not null default 3 check (best_minimum_age between 0 and 18),
  avoid_with_baby boolean not null default false,
  avoid_with_toddler boolean not null default false,
  requires_car boolean not null default true,
  requires_4x4 boolean not null default false,
  requires_private_guide boolean not null default false,
  stroller_friendly boolean not null default false,
  baby_carrier_recommended boolean not null default true,
  nap_friendly boolean not null default false,
  medical_structure_warning boolean not null default false,
  long_drive_warning boolean not null default true,
  boat_warning boolean not null default false,
  altitude_warning boolean not null default false,
  heat_warning boolean not null default false,
  cold_warning boolean not null default false,
  rain_warning boolean not null default false,
  limited_food_options_warning boolean not null default false,
  main_hassles text[] not null default '{}',
  hassle_mitigation_tips text[] not null default '{}',
  sem_perrengue_strategy text,
  recommended_trip_pace text not null default 'leve'
    check (recommended_trip_pace in ('leve', 'moderado', 'intenso')),
  max_activities_per_day_with_kids integer not null default 1 check (max_activities_per_day_with_kids between 1 and 4),
  recommended_lodging_location text,
  when_to_avoid text[] not null default '{}',
  when_it_works_well text[] not null default '{}',
  honest_summary text,
  short_hassle_alert text,
  better_alternative_slugs text[] not null default '{}',
  curation_source text not null default 'editorial',
  updated_at timestamptz not null default now()
);

create index if not exists idx_destination_family_hassle_level
  on public.destination_family_hassle(family_hassle_level, best_minimum_age);

alter table if exists public.destinations
  add column if not exists family_hassle_level text,
  add column if not exists hassle_score integer,
  add column if not exists baby_friendliness_score integer,
  add column if not exists toddler_friendliness_score integer,
  add column if not exists kids_6_10_friendliness_score integer,
  add column if not exists teen_friendliness_score integer,
  add column if not exists best_minimum_age integer,
  add column if not exists avoid_with_baby boolean,
  add column if not exists avoid_with_toddler boolean,
  add column if not exists requires_car boolean,
  add column if not exists requires_4x4 boolean,
  add column if not exists requires_private_guide boolean,
  add column if not exists stroller_friendly boolean,
  add column if not exists baby_carrier_recommended boolean,
  add column if not exists nap_friendly boolean,
  add column if not exists medical_structure_warning boolean,
  add column if not exists long_drive_warning boolean,
  add column if not exists boat_warning boolean,
  add column if not exists altitude_warning boolean,
  add column if not exists heat_warning boolean,
  add column if not exists cold_warning boolean,
  add column if not exists rain_warning boolean,
  add column if not exists limited_food_options_warning boolean,
  add column if not exists main_hassles text[],
  add column if not exists hassle_mitigation_tips text[],
  add column if not exists sem_perrengue_strategy text,
  add column if not exists recommended_trip_pace text,
  add column if not exists max_activities_per_day_with_kids integer,
  add column if not exists recommended_lodging_location text,
  add column if not exists when_to_avoid text[],
  add column if not exists when_it_works_well text[],
  add column if not exists honest_summary text,
  add column if not exists short_hassle_alert text,
  add column if not exists better_alternative_slugs text[];

alter table if exists public.family_destination_catalog_1001
  add column if not exists family_hassle_level text,
  add column if not exists hassle_score integer,
  add column if not exists baby_friendliness_score integer,
  add column if not exists toddler_friendliness_score integer,
  add column if not exists kids_6_10_friendliness_score integer,
  add column if not exists teen_friendliness_score integer,
  add column if not exists best_minimum_age integer,
  add column if not exists avoid_with_baby boolean,
  add column if not exists avoid_with_toddler boolean,
  add column if not exists requires_car boolean,
  add column if not exists requires_4x4 boolean,
  add column if not exists requires_private_guide boolean,
  add column if not exists stroller_friendly boolean,
  add column if not exists baby_carrier_recommended boolean,
  add column if not exists nap_friendly boolean,
  add column if not exists medical_structure_warning boolean,
  add column if not exists long_drive_warning boolean,
  add column if not exists boat_warning boolean,
  add column if not exists altitude_warning boolean,
  add column if not exists heat_warning boolean,
  add column if not exists cold_warning boolean,
  add column if not exists rain_warning boolean,
  add column if not exists limited_food_options_warning boolean,
  add column if not exists main_hassles text[],
  add column if not exists hassle_mitigation_tips text[],
  add column if not exists sem_perrengue_strategy text,
  add column if not exists recommended_trip_pace text,
  add column if not exists max_activities_per_day_with_kids integer,
  add column if not exists recommended_lodging_location text,
  add column if not exists when_to_avoid text[],
  add column if not exists when_it_works_well text[],
  add column if not exists honest_summary text,
  add column if not exists short_hassle_alert text,
  add column if not exists better_alternative_slugs text[];
